version: 2.1

orbs:
  codecov: codecov/codecov@3.1.1
  node: circleci/node@4.7.0

jobs:
  upload-cov:
    machine:
      image: ubuntu-2004:202010-01
    environment:
      COVERAGE_PATH: "./tmp/cov"
    steps:
      - codecov/upload

workflows:
  sample:
    jobs:
      - node/test:
          version: '16.10'
          pkg-manager: npm
      - upload-cov
            