version: 2.1

orbs:
  codecov: codecov/codecov@3.1.1
  node: circleci/node@4.7.0
environment:
  COVERAGE_PATH: "./tmp/coverage"
workflows:
  sample:
    jobs:
      - node/test:
          version: '16.10'
          pkg-manager: npm
          post-steps:
            - codecov/upload